name:  CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test on Java 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [11, 17, 21]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Run Maven tests
        run: mvn test
